version: '3'

services:

  app:
    build: .
    container_name: nestjs-loopback-app
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: nestjs-loopback-elasticsearch
    environment:
      - discovery.type=single-node
    volumes:
      - nestjs-loopback-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    container_name: nestjs-loopback-kibana
    ports:
      - 5601:5601
    networks:
      - default

volumes:
  nestjs-loopback-elasticsearch:
    external: true
